os: linux
sudo: false
language: python

python:
  - "3.7"
install:
  - pip install -r requirements.txt
script:
  - nosetests tests
cache:
  - pip
branches:
  only:
    - master

notifications:
  email: false
